name: Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: install app dependencies and build it
      run: yarn && yarn build
      
    - uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "v__VERSION__"
        releaseBody: ""
        releaseDraft: true
        prerelease: false
